# Configuración del nombre de la aplicación
spring.application.name=producto-service

# Configuración del puerto del servicio
server.port=8080

# Configuracion de la base de datosß
## Configuración de la url de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/curso_springboot
## Configuración del usuario de la base de datos
spring.datasource.username=devdb
## Configuración de la contraseña de la base de datos
spring.datasource.password=a1b2c3d4

# Configuración de la persistencia JPA
## Configuración de la generación de la base de datos
## Ajustamos la estrategia DDL
## create-drop: Crea la base de datos y la elimina al finalizar la aplicación
## create: Crea la base de datos
## update: Actualiza la base de datos
## validate: Valida la base de datos
## none: No realiza ninguna acción
spring.jpa.hibernate.ddl-auto=create-drop

## Habilitamos las transacciones durante el render de la vista
spring.jpa.open-in-view=true

## En caso de ser necesario se especifica el dialecto SQL
### spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

## Especificamos que nos muestre las consultas SQL en la terminal
spring.jpa.show-sql=true

## Habilitamos o desabilitamos las referencias circulares
### Si la clase A tiene un atributo de tipo B y la clase B tiene un atributo de tipo A, Spring detecta una referencia circular y lanza un error al intentar instanciar ambos.
### Con spring.main.allow-circular-references=true, Spring usa proxies dinámicos para retrasar la inyección y evitar el error.
### Cuando hay una dependencia circular, Spring en lugar de crear A y B al mismo tiempo, crea un proxy de A, lo inyecta en B, y luego lo enlaza correctamente cuando A esté listo.
spring.main.allow-circular-references=true

## Configurando el tamaño del pool de conexiones
spring.datasource.hikari.maximum-pool-size=50

## Configurando el tiempo de espera de la conexión
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

## Configurando la cantidad minima de conexiones con poca carga
spring.datasource.hikari.minimum-idle=10

## Configurando el tiempo de espera para mantener la conexión viva
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-test-query=SELECT 1

# Depuracion de la aplicacion

## Podemos tener diferentes niveles de depuracion tales como:
## DEBUG, INFO, WARN, ERROR, FATAL, OFF

## Habilitamos la depuracion de la aplicacion
logging.level.org.springframework=ERROR

## Habilitamos la depuracion de las peticiones web
logging.level.web=INFO

## Habilitamos la depuracion de las peticiones SQL
logging.level.org.hibernate.SQL=DEBUG

logging.level.root=ERROR
logging.level.com.zaxxer.hikari=ERROR
logging.level.org.hibernate=ERROR

